# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a base Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the pyproject.toml and other necessary files
COPY pyproject.toml .

# Install hatchling and project dependencies
RUN pip install hatchling && hatch install

# Copy the application source code
COPY src/ ./src

# Run the server
CMD ["python", "src/notes/server.py"]
